import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

export type LanguageCode = 'en' | 'ms' | 'zh';

type Dictionary = Record<string, string>;

type Translations = Record<LanguageCode, Dictionary>;

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const STORAGE_KEY = 'fraud-shield-language-v1';

const translations: Translations = {
  en: {
    'language.label': 'Language',
    'language.english': 'English',
    'language.malay': 'Malay',
    'language.chinese': 'Chinese',

    'nav.overview': 'OVERVIEW',
    'nav.dashboard': 'DASHBOARD',
    'nav.admin': 'ADMIN',
    'nav.transactions': 'TRANSACTIONS',
    'nav.searchPlaceholder': 'Search here...',
    'nav.startTour': 'START TOUR',
    'nav.profileSettings': 'PROFILE / SETTINGS',

    'profile.title': 'Profile & Payment Security',
    'profile.subtitle': 'Manage account details, verification status, and linked bank cards.',
    'profile.accountDetails': 'Account Details',
    'profile.saveChanges': 'Save Changes',
    'profile.fullName': 'Full Name',
    'profile.email': 'Email',
    'profile.phoneNumber': 'Phone Number',
    'profile.nationality': 'Nationality',
    'profile.languagePreference': 'Language Preference',
    'profile.languageHint': 'Choose your display language for the app interface.',
    'profile.applicationTheme': 'Application Theme',
    'profile.switchDark': 'Switch to Dark',
    'profile.switchLight': 'Switch to Light',
    'profile.walletPinProtection': 'Wallet PIN Protection',
    'profile.updated': 'Profile updated successfully.',

    'dashboard.blockedFraud': 'BLOCKED FRAUD',
    'dashboard.totalTransactions': 'TOTAL TRANSACTIONS',
    'dashboard.fraudRate': 'FRAUD RATE',
    'dashboard.avgReviewTime': 'AVG REVIEW TIME',
    'dashboard.liveFromSimulator': 'Live from transaction simulator',
    'dashboard.flaggedPending': '{count} flagged pending review',
    'dashboard.flaggedBlockedOverTotal': 'Flagged + blocked / total',
    'dashboard.avgFinalRiskScore': 'Average final risk score',
    'dashboard.riskDistribution': 'RISK SCORE DISTRIBUTION',
    'dashboard.low': 'Low',
    'dashboard.medium': 'Medium',
    'dashboard.high': 'High',
    'dashboard.realTimeAlerts': 'REAL-TIME ALERTS',
    'dashboard.newCount': '{count} NEW',
    'dashboard.noAlerts': 'No alerts yet. Run a flagged or blocked transaction to populate this panel.',
    'dashboard.recentTransactions': 'RECENT TRANSACTIONS',
    'dashboard.clearDemoData': 'Clear Demo Data',
    'dashboard.transactionId': 'Transaction ID',
    'dashboard.user': 'User',
    'dashboard.amount': 'Amount',
    'dashboard.dateTime': 'Date & Time',
    'dashboard.riskScore': 'Risk Score',
    'dashboard.status': 'Status',
    'dashboard.blocked': 'Blocked',
    'dashboard.flagged': 'Flagged',
    'dashboard.approved': 'Approved',
    'dashboard.noTransactions': 'No transactions yet. Submit a transaction from the Transaction page to populate this dashboard.',

    'notFound.title': 'Page Not Found',
    'notFound.line1': 'Sorry, the page you are looking for does not exist.',
    'notFound.line2': 'It may have been moved or deleted.',
    'notFound.goHome': 'Go Home',

    'landing.hero.highlight': 'Safeguard',
    'landing.hero.titleRest': 'Every Transaction',
    'landing.hero.subtitleLine1': 'Our intelligent engine analyzes millions of data points in milliseconds,',
    'landing.hero.subtitleLine2': 'providing your team with actionable insights to protect users from digital payment fraud.',
    'landing.hero.startTour': 'Start Guided Tour',
    'landing.hero.playSwipeShield': 'Play SwipeShield',
    'landing.hero.viewDocs': 'View Documentation',
    'landing.features.headingLine1': 'Your trusted partner for',
    'landing.features.headingLine2': 'fraud prevention.',
    'landing.features.subLine1': 'Our system unites and secures a growing',
    'landing.features.subLine2': 'ecosystem of specialized financial data to eliminate threats.',
    'landing.features.f1Title': 'Real-Time Detection',
    'landing.features.f1Desc': 'Analyzes transactions instantly and predicts fraud.',
    'landing.features.f2Title': 'AI Risk Scoring',
    'landing.features.f2Desc': 'Each transaction receives a probability score to identify risk.',
    'landing.features.f3Title': 'Smart Monitoring',
    'landing.features.f3Desc': 'Tracks transaction patterns such as location and behavior.',
    'landing.features.f4Title': 'Fraud Alerts',
    'landing.features.f4Desc': 'Flags high-risk transactions effectively.',
    'landing.hiw.title': 'How It Works',
    'landing.hiw.s1Title': 'User submits a transaction',
    'landing.hiw.s1Desc': 'The transaction is securely initiated through the digital gateway.',
    'landing.hiw.s2Title': 'System analyzes transaction features',
    'landing.hiw.s2Desc': 'Cross-checks device fingerprint, location, and historical patterns.',
    'landing.hiw.s3Title': 'ML model calculates fraud probability',
    'landing.hiw.s3Desc': 'Machine learning algorithms assign a risk likelihood to the behavior.',
    'landing.hiw.s4Title': 'Risk score is generated',
    'landing.hiw.s4Desc': 'A specific risk value determines if intervention is required.',
    'landing.hiw.s5Title': 'Dashboard displays result',
    'landing.hiw.s5Desc': 'Alerts the user and generates reports automatically.',
    'landing.lesson.badge': 'Fraud 101',
    'landing.lesson.title': 'Scam Safety Game',
    'landing.lesson.subtitle': 'Clear 3 learning rounds and 3 quiz rounds.',
    'landing.lesson.scamAware': 'Scam Aware',
    'landing.lesson.safetyPoints': 'Safety Points',
    'landing.lesson.completedPrefix': 'Lesson completed',
    'landing.lesson.correct': 'correct',
    'landing.lesson.completedSuffix': 'Review anytime to refresh your safety habits.',
    'landing.lesson.intro': 'Learn the basics in 3 short cards and answer 3 quick questions.',
    'landing.lesson.playAgain': 'Play Again',
    'landing.lesson.startGame': 'Start Game',
    'landing.lesson.learningRound': 'Learning Round',
    'landing.lesson.quizRound': 'Quiz Round',
    'landing.lesson.rewardRound': 'Reward Round',
    'landing.lesson.step': 'Step',
    'landing.lesson.correctFeedback': 'Correct. Safe choice.',
    'landing.lesson.wrongFeedback': 'Try safer action next time.',
    'landing.lesson.missionResult': 'Mission Result',
    'landing.lesson.youScored': 'You scored {score}/3. Nice work learning scam safety.',
    'landing.lesson.rewardLabel': 'Reward: +10 Safety Points',
    'landing.lesson.nextRound': 'Next Round',
    'landing.lesson.claimReward': 'Claim Reward and Finish',
    'landing.lesson.maybeLater': 'Maybe Later',
    'landing.lesson.selectAnswer': 'Select one answer before continuing.',
    'landing.lesson.card1Title': 'What Is Fraud?',
    'landing.lesson.card1Desc': 'Fraud means someone lies or hides the truth to get your money, goods, or personal details.',
    'landing.lesson.card2Title': 'How Scammers Usually Attack',
    'landing.lesson.card2Desc': 'They may pretend to be a buyer, bank, or officer and rush you to act fast without checking.',
    'landing.lesson.card3Title': 'Simple Safety Rule',
    'landing.lesson.card3Desc': 'Stop 10 seconds and check 3 things: name, account number, and payment reason.',
    'landing.lesson.q1.question': 'Which sentence explains fraud best?',
    'landing.lesson.q1.o1': 'A normal business payment',
    'landing.lesson.q1.o2': 'A lie or trick used to take someone\'s money',
    'landing.lesson.q1.o3': 'Any late payment fee',
    'landing.lesson.q2.question': 'A person asks you to transfer money urgently and says no need to check. What is safest?',
    'landing.lesson.q2.o1': 'Transfer now because it is urgent',
    'landing.lesson.q2.o2': 'Verify identity first with a trusted contact',
    'landing.lesson.q2.o3': 'Send half now and half later',
    'landing.lesson.q3.question': 'Before sending money, what should you always check?',
    'landing.lesson.q3.o1': 'Only the transfer amount',
    'landing.lesson.q3.o2': 'Recipient name, account number, and reason',
    'landing.lesson.q3.o3': 'Only the message screenshot',

    'guardian.title': 'Guardian Notification Feed',
    'guardian.subtitle': 'Shows alerts triggered by high-risk transfers or risky QR scans.',
    'guardian.backToProfile': 'Back to Profile',
    'guardian.refresh': 'Refresh',
    'guardian.guardianAccount': 'Guardian Account',
    'guardian.chooseGuardian': 'Choose guardian',
    'guardian.currentGuardian': 'Current Guardian',
    'guardian.notSelected': 'Not selected',
    'guardian.noEmail': 'No email',
    'guardian.noPhone': 'No phone',
    'guardian.waitingDecision': 'Transactions Waiting for Guardian Decision',
    'guardian.pendingCount': '{count} pending',
    'guardian.noPending': 'No pending approvals right now.',
    'guardian.risk': 'risk',
    'guardian.to': 'to',
    'guardian.approvalId': 'Approval ID',
    'guardian.expires': 'Expires',
    'guardian.approveTransaction': 'Approve Transaction',
    'guardian.rejectForSafety': 'Reject for Safety',
    'guardian.liveAlertInbox': 'Live Alert Inbox',
    'guardian.alertCount': '{count} alerts',
    'guardian.noHighRiskAlerts': 'No high-risk alerts yet. Trigger a risky transfer or suspicious QR scan to see this feed update.',
    'guardian.pagePath': 'Page path',
    'guardian.noteApprove': 'Approved after guardian review.',
    'guardian.noteReject': 'Rejected due to scam concern.',
    'guardian.approvedByGuardian': 'Transaction approved by guardian.',
    'guardian.rejectedByGuardian': 'Transaction rejected by guardian.',
    'guardian.errorLoadGuardians': 'Could not load guardians.',
    'guardian.errorLoadNotifications': 'Could not load guardian notifications.',
    'guardian.errorLoadPending': 'Could not load pending approvals.',
    'guardian.errorRecordDecision': 'Unable to record decision.',
    'guardian.errorLoadDataNow': 'Unable to load guardian data right now.',
    'guardian.errorLoadNotificationsNow': 'Unable to load notifications right now.',

    'swipe.channel.sms': 'SMS',
    'swipe.channel.bankMessage': 'Bank Message',
    'swipe.channel.email': 'Email',
    'swipe.channel.whatsapp': 'WhatsApp',
    'swipe.channel.videoCall': 'Video Call',
    'swipe.channel.message': 'Message',
    'swipe.level.veryEasy': 'Very Easy',
    'swipe.level.easy': 'Easy',
    'swipe.level.medium': 'Medium',
    'swipe.level.hard': 'Hard',
    'swipe.level.extreme': 'Extreme',
    'swipe.levelOf': 'Level {current} of {total}',
    'swipe.swipeLeftScam': 'Swipe Left: Scam',
    'swipe.swipeRightSafe': 'Swipe Right: Safe',
    'swipe.dragOrTap': 'Drag card or tap buttons',
    'swipe.correct': 'Correct',
    'swipe.notQuite': 'Not Quite',
    'swipe.feedbackChoice': 'You chose {choice}. Correct answer: {expected}.',
    'swipe.redFlag': 'Red Flag',
    'swipe.whyThisMatters': 'Why This Matters',
    'swipe.excellent': 'Excellent',
    'swipe.goodWork': 'Good Work',
    'swipe.practiceMore': 'Practice More',
    'swipe.accuracy': 'Accuracy',
    'swipe.frictionTier': 'Friction tier',
    'swipe.savedOffline': 'Saved locally (offline mode)',
    'swipe.syncedApi': 'Synced with API',
    'swipe.playAgain': 'Play Again',
    'swipe.backToApp': 'Back to App',
    'swipe.nextStep.strict': 'Profile set to STRICT security mode.',
    'swipe.nextStep.balanced': 'Profile set to BALANCED security mode.',
    'swipe.nextStep.light': 'Profile set to SMART security mode.',
    'swipe.surface.messages': 'Messages',
    'swipe.surface.replyOtp': 'Reply OTP',
    'swipe.surface.ignore': 'Ignore',
    'swipe.surface.maybankNotice': 'MAYBANK OFFICIAL NOTICE',
    'swipe.surface.subject': 'Subject',
    'swipe.surface.subjectOtp': 'Unusual Login From Singapore',
    'swipe.surface.subjectRefund': 'Unclaimed Tax Refund - RM 850.50',
    'swipe.surface.replyWithOtp': 'Reply with OTP',
    'swipe.surface.goSecurePortal': 'Go to Secure Portal',
    'swipe.surface.online': 'online',
    'swipe.surface.beneficiaryMismatch': 'Beneficiary name mismatch',
    'swipe.surface.incomingCall': 'Incoming Video Call',
    'swipe.surface.unstable': 'UNSTABLE',
    'swipe.surface.qrPayRequest': 'QR pay request: RM 1,000 to third-party driver',
    'swipe.s1.title': 'Urgent Account Lock',
    'swipe.s1.preview': 'Unknown mobile number',
    'swipe.s1.message': 'Your bank account is BLOCKED! Click immediately to verify: bit.ly/fake-bank-login',
    'swipe.s1.redFlag': 'Extreme urgency + shortened URL from a non-official number.',
    'swipe.s1.education': 'Banks will never send account-critical links via a standard mobile phone number.',
    'swipe.s2.title': 'Official OTP Request',
    'swipe.s2.preview': 'Logo + polished UI',
    'swipe.s2.message': 'We detected a login from Singapore. Reply with your 6-digit OTP to cancel the transaction.',
    'swipe.s2.redFlag': 'Asking you to reply with OTP directly.',
    'swipe.s2.education': 'Your OTP is your digital signature. Sharing it by reply is like giving a thief your house keys.',
    'swipe.s3.title': 'LHDN Tax Refund',
    'swipe.s3.preview': 'Looks like a government letterhead',
    'swipe.s3.message': 'You have an unclaimed tax refund of RM 850.50. Login to our Secure Portal to submit bank details.',
    'swipe.s3.redFlag': 'Direct refund link and non-official email domain.',
    'swipe.s3.education': 'Always navigate to the official gov.my website manually. Never trust a direct refund link in email.',
    'swipe.s4.title': 'Struggling Friend',
    'swipe.s4.sender': 'Auntie Mary',
    'swipe.s4.preview': 'Real profile photo + emotional request',
    'swipe.s4.message': 'Hi dear, I am at the grocery store and my card failed. Please transfer RM 200 to this account now.',
    'swipe.s4.redFlag': 'Pressure + transfer request to unfamiliar account owner (money mule risk).',
    'swipe.s4.education': 'Always call the person directly to verify their voice before sending money to unfamiliar account numbers.',
    'swipe.s5.title': 'Deepfake / AI Call',
    'swipe.s5.sender': 'Family Emergency Call',
    'swipe.s5.preview': 'Dark-room video + urgent QR payment',
    'swipe.s5.message': 'I got into an accident, phone dying, send RM 1,000 to this tow truck QR code NOW.',
    'swipe.s5.redFlag': 'High-pressure emergency + pay third party instantly via QR.',
    'swipe.s5.education': 'Scammers use AI to mimic faces and voices. Set a family safety word for real emergencies.',

    'tx.autoReport.title': 'Auto-Report Pipeline',
    'tx.autoReport.descVerify': 'Prepare an external safety report for this scam so the incident can be escalated beyond the app.',
    'tx.autoReport.descBlocked': 'Export this blocked scam to external safety channels for follow-up.',
    'tx.autoReport.button': 'Report Fraud (MCMC + Google)',
    'tx.autoReport.submitting': 'Submitting...',
    'tx.autoReport.caseReported': 'CASE REPORTED',
    'tx.autoReport.successLine1': 'This scam has been successfully reported to security authorities. Thank you for helping protect others.',
    'tx.autoReport.reportedTo': 'Reported to:',
    'tx.autoReport.thankYou': 'Thank you for keeping the community safe!',
    'tx.autoReport.close': 'Close',

    'admin.badge': 'Admin Interface',
    'admin.title': 'Agency Command Center',
    'admin.subtitle': 'Decision-grade view for banks and agencies to track fraud pressure and savings impact.',
    'admin.kpiSavings': 'Estimated Agency Savings',
    'admin.kpiBlocked': 'Blocked Scam Cases',
    'admin.kpiFlagged': 'Flagged Investigations',
    'admin.kpiSavingsDesc': 'Prevented scam outflow plus reduced manual triage cost from automated blocking and prioritization.',
    'admin.kpiBlockedDesc': 'High-risk transactions prevented before losses happened.',
    'admin.kpiFlaggedDesc': 'Cases triaged early for focused analyst follow-up.',
    'admin.heatmapTitle': 'Fraud Heatmap',
    'admin.heatmapSubtitle': 'Incidents by weekday and time window',
    'admin.intensity': 'Intensity:',
    'admin.intensityLow': 'Low',
    'admin.intensityMedium': 'Medium',
    'admin.intensityHigh': 'High',
    'admin.savingsChartTitle': 'Agency Savings (6 Months)',
    'admin.savingsChartSubtitle': 'Modelled avoided loss + triage savings',
    'admin.savingsFormula': 'Savings formula: 82% of blocked transaction amount + MYR 18 operational cost avoided per flagged or blocked case.',
  },
  ms: {
    'language.label': 'Bahasa',
    'language.english': 'Inggeris',
    'language.malay': 'Melayu',
    'language.chinese': 'Cina',

    'nav.overview': 'GAMBARAN',
    'nav.dashboard': 'PAPAN PEMUKA',
    'nav.admin': 'PENTADBIR',
    'nav.transactions': 'TRANSAKSI',
    'nav.searchPlaceholder': 'Cari di sini...',
    'nav.startTour': 'MULA LAWATAN',
    'nav.profileSettings': 'PROFIL / TETAPAN',

    'profile.title': 'Profil & Keselamatan Pembayaran',
    'profile.subtitle': 'Urus butiran akaun, status pengesahan, dan kad bank yang dipautkan.',
    'profile.accountDetails': 'Butiran Akaun',
    'profile.saveChanges': 'Simpan Perubahan',
    'profile.fullName': 'Nama Penuh',
    'profile.email': 'E-mel',
    'profile.phoneNumber': 'Nombor Telefon',
    'profile.nationality': 'Kewarganegaraan',
    'profile.languagePreference': 'Pilihan Bahasa',
    'profile.languageHint': 'Pilih bahasa paparan untuk antara muka aplikasi.',
    'profile.applicationTheme': 'Tema Aplikasi',
    'profile.switchDark': 'Tukar ke Gelap',
    'profile.switchLight': 'Tukar ke Cerah',
    'profile.walletPinProtection': 'Perlindungan PIN Dompet',
    'profile.updated': 'Profil berjaya dikemas kini.',

    'dashboard.blockedFraud': 'PENIPUAN DISEKAT',
    'dashboard.totalTransactions': 'JUMLAH TRANSAKSI',
    'dashboard.fraudRate': 'KADAR PENIPUAN',
    'dashboard.avgReviewTime': 'PURATA MASA SEMAKAN',
    'dashboard.liveFromSimulator': 'Data langsung dari simulator transaksi',
    'dashboard.flaggedPending': '{count} ditandai menunggu semakan',
    'dashboard.flaggedBlockedOverTotal': 'Ditandai + disekat / jumlah',
    'dashboard.avgFinalRiskScore': 'Purata skor risiko akhir',
    'dashboard.riskDistribution': 'TABURAN SKOR RISIKO',
    'dashboard.low': 'Rendah',
    'dashboard.medium': 'Sederhana',
    'dashboard.high': 'Tinggi',
    'dashboard.realTimeAlerts': 'AMARAN MASA NYATA',
    'dashboard.newCount': '{count} BAHARU',
    'dashboard.noAlerts': 'Belum ada amaran. Jalankan transaksi ditandai atau disekat untuk mengisi panel ini.',
    'dashboard.recentTransactions': 'TRANSAKSI TERKINI',
    'dashboard.clearDemoData': 'Padam Data Demo',
    'dashboard.transactionId': 'ID Transaksi',
    'dashboard.user': 'Pengguna',
    'dashboard.amount': 'Jumlah',
    'dashboard.dateTime': 'Tarikh & Masa',
    'dashboard.riskScore': 'Skor Risiko',
    'dashboard.status': 'Status',
    'dashboard.blocked': 'Disekat',
    'dashboard.flagged': 'Ditandai',
    'dashboard.approved': 'Diluluskan',
    'dashboard.noTransactions': 'Belum ada transaksi. Hantar transaksi dari halaman Transaction untuk memaparkan papan pemuka ini.',

    'notFound.title': 'Halaman Tidak Ditemui',
    'notFound.line1': 'Maaf, halaman yang anda cari tidak wujud.',
    'notFound.line2': 'Halaman ini mungkin telah dipindahkan atau dipadamkan.',
    'notFound.goHome': 'Kembali ke Laman Utama',

    'landing.hero.highlight': 'Lindungi',
    'landing.hero.titleRest': 'Setiap Transaksi',
    'landing.hero.subtitleLine1': 'Enjin pintar kami menganalisis jutaan titik data dalam milisaat,',
    'landing.hero.subtitleLine2': 'memberi pasukan anda pandangan boleh tindakan untuk melindungi pengguna daripada penipuan pembayaran digital.',
    'landing.hero.startTour': 'Mula Lawatan Berpanduan',
    'landing.hero.playSwipeShield': 'Main SwipeShield',
    'landing.hero.viewDocs': 'Lihat Dokumentasi',
    'landing.features.headingLine1': 'Rakan dipercayai anda untuk',
    'landing.features.headingLine2': 'pencegahan penipuan.',
    'landing.features.subLine1': 'Sistem kami menyatukan dan melindungi',
    'landing.features.subLine2': 'ekosistem data kewangan khusus yang semakin berkembang untuk menghapuskan ancaman.',
    'landing.features.f1Title': 'Pengesanan Masa Nyata',
    'landing.features.f1Desc': 'Menganalisis transaksi serta-merta dan meramal penipuan.',
    'landing.features.f2Title': 'Pemarkahan Risiko AI',
    'landing.features.f2Desc': 'Setiap transaksi menerima skor kebarangkalian untuk mengenal pasti risiko.',
    'landing.features.f3Title': 'Pemantauan Pintar',
    'landing.features.f3Desc': 'Menjejak corak transaksi seperti lokasi dan tingkah laku.',
    'landing.features.f4Title': 'Amaran Penipuan',
    'landing.features.f4Desc': 'Menandai transaksi berisiko tinggi dengan berkesan.',
    'landing.hiw.title': 'Cara Ia Berfungsi',
    'landing.hiw.s1Title': 'Pengguna menghantar transaksi',
    'landing.hiw.s1Desc': 'Transaksi dimulakan secara selamat melalui gerbang digital.',
    'landing.hiw.s2Title': 'Sistem menganalisis ciri transaksi',
    'landing.hiw.s2Desc': 'Semak silang cap jari peranti, lokasi dan corak sejarah.',
    'landing.hiw.s3Title': 'Model ML mengira kebarangkalian penipuan',
    'landing.hiw.s3Desc': 'Algoritma pembelajaran mesin memberi kemungkinan risiko kepada tingkah laku.',
    'landing.hiw.s4Title': 'Skor risiko dijana',
    'landing.hiw.s4Desc': 'Nilai risiko khusus menentukan sama ada intervensi diperlukan.',
    'landing.hiw.s5Title': 'Papan pemuka memaparkan hasil',
    'landing.hiw.s5Desc': 'Memberi amaran kepada pengguna dan menjana laporan secara automatik.',
    'landing.lesson.badge': 'Penipuan 101',
    'landing.lesson.title': 'Permainan Keselamatan Scam',
    'landing.lesson.subtitle': 'Lengkapkan 3 pusingan pembelajaran dan 3 pusingan kuiz.',
    'landing.lesson.scamAware': 'Peka Scam',
    'landing.lesson.safetyPoints': 'Mata Keselamatan',
    'landing.lesson.completedPrefix': 'Pelajaran selesai',
    'landing.lesson.correct': 'betul',
    'landing.lesson.completedSuffix': 'Ulang kaji bila-bila masa untuk menyegarkan tabiat keselamatan anda.',
    'landing.lesson.intro': 'Pelajari asas melalui 3 kad ringkas dan jawab 3 soalan cepat.',
    'landing.lesson.playAgain': 'Main Semula',
    'landing.lesson.startGame': 'Mula Permainan',
    'landing.lesson.learningRound': 'Pusingan Pembelajaran',
    'landing.lesson.quizRound': 'Pusingan Kuiz',
    'landing.lesson.rewardRound': 'Pusingan Ganjaran',
    'landing.lesson.step': 'Langkah',
    'landing.lesson.correctFeedback': 'Betul. Pilihan yang selamat.',
    'landing.lesson.wrongFeedback': 'Cuba tindakan yang lebih selamat lain kali.',
    'landing.lesson.missionResult': 'Keputusan Misi',
    'landing.lesson.youScored': 'Skor anda {score}/3. Syabas mempelajari keselamatan scam.',
    'landing.lesson.rewardLabel': 'Ganjaran: +10 Mata Keselamatan',
    'landing.lesson.nextRound': 'Pusingan Seterusnya',
    'landing.lesson.claimReward': 'Tuntut Ganjaran dan Tamat',
    'landing.lesson.maybeLater': 'Mungkin Nanti',
    'landing.lesson.selectAnswer': 'Pilih satu jawapan sebelum meneruskan.',
    'landing.lesson.card1Title': 'Apakah Itu Penipuan?',
    'landing.lesson.card1Desc': 'Penipuan bermaksud seseorang menipu atau menyembunyikan kebenaran untuk mendapatkan wang, barangan atau maklumat peribadi anda.',
    'landing.lesson.card2Title': 'Cara Scammer Selalu Menyerang',
    'landing.lesson.card2Desc': 'Mereka mungkin menyamar sebagai pembeli, bank atau pegawai dan mendesak anda bertindak pantas tanpa semakan.',
    'landing.lesson.card3Title': 'Peraturan Keselamatan Mudah',
    'landing.lesson.card3Desc': 'Berhenti 10 saat dan semak 3 perkara: nama, nombor akaun dan sebab pembayaran.',
    'landing.lesson.q1.question': 'Ayat manakah paling tepat menerangkan penipuan?',
    'landing.lesson.q1.o1': 'Pembayaran perniagaan biasa',
    'landing.lesson.q1.o2': 'Pembohongan atau helah untuk mengambil wang seseorang',
    'landing.lesson.q1.o3': 'Sebarang caj lewat bayar',
    'landing.lesson.q2.question': 'Seseorang minta anda pindah wang segera dan kata tidak perlu semak. Apa yang paling selamat?',
    'landing.lesson.q2.o1': 'Pindah sekarang sebab mendesak',
    'landing.lesson.q2.o2': 'Sahkan identiti dahulu melalui kontak dipercayai',
    'landing.lesson.q2.o3': 'Hantar separuh dulu, separuh kemudian',
    'landing.lesson.q3.question': 'Sebelum hantar wang, apa yang mesti anda semak?',
    'landing.lesson.q3.o1': 'Jumlah pindahan sahaja',
    'landing.lesson.q3.o2': 'Nama penerima, nombor akaun dan sebab',
    'landing.lesson.q3.o3': 'Tangkapan skrin mesej sahaja',

    'guardian.title': 'Suapan Notifikasi Penjaga',
    'guardian.subtitle': 'Menunjukkan amaran yang dicetuskan oleh pemindahan berisiko tinggi atau imbasan QR berisiko.',
    'guardian.backToProfile': 'Kembali ke Profil',
    'guardian.refresh': 'Segar Semula',
    'guardian.guardianAccount': 'Akaun Penjaga',
    'guardian.chooseGuardian': 'Pilih penjaga',
    'guardian.currentGuardian': 'Penjaga Semasa',
    'guardian.notSelected': 'Belum dipilih',
    'guardian.noEmail': 'Tiada e-mel',
    'guardian.noPhone': 'Tiada telefon',
    'guardian.waitingDecision': 'Transaksi Menunggu Keputusan Penjaga',
    'guardian.pendingCount': '{count} menunggu',
    'guardian.noPending': 'Tiada kelulusan menunggu sekarang.',
    'guardian.risk': 'risiko',
    'guardian.to': 'kepada',
    'guardian.approvalId': 'ID Kelulusan',
    'guardian.expires': 'Tamat',
    'guardian.approveTransaction': 'Luluskan Transaksi',
    'guardian.rejectForSafety': 'Tolak Demi Keselamatan',
    'guardian.liveAlertInbox': 'Peti Masuk Amaran Langsung',
    'guardian.alertCount': '{count} amaran',
    'guardian.noHighRiskAlerts': 'Belum ada amaran berisiko tinggi. Cetuskan pindahan berisiko atau imbasan QR mencurigakan untuk melihat suapan ini dikemas kini.',
    'guardian.pagePath': 'Laluan halaman',
    'guardian.noteApprove': 'Diluluskan selepas semakan penjaga.',
    'guardian.noteReject': 'Ditolak kerana kebimbangan penipuan.',
    'guardian.approvedByGuardian': 'Transaksi diluluskan oleh penjaga.',
    'guardian.rejectedByGuardian': 'Transaksi ditolak oleh penjaga.',
    'guardian.errorLoadGuardians': 'Tidak dapat memuatkan penjaga.',
    'guardian.errorLoadNotifications': 'Tidak dapat memuatkan notifikasi penjaga.',
    'guardian.errorLoadPending': 'Tidak dapat memuatkan kelulusan menunggu.',
    'guardian.errorRecordDecision': 'Tidak dapat merekodkan keputusan.',
    'guardian.errorLoadDataNow': 'Tidak dapat memuatkan data penjaga sekarang.',
    'guardian.errorLoadNotificationsNow': 'Tidak dapat memuatkan notifikasi sekarang.',

    'swipe.channel.sms': 'SMS',
    'swipe.channel.bankMessage': 'Mesej Bank',
    'swipe.channel.email': 'E-mel',
    'swipe.channel.whatsapp': 'WhatsApp',
    'swipe.channel.videoCall': 'Panggilan Video',
    'swipe.channel.message': 'Mesej',
    'swipe.level.veryEasy': 'Sangat Mudah',
    'swipe.level.easy': 'Mudah',
    'swipe.level.medium': 'Sederhana',
    'swipe.level.hard': 'Sukar',
    'swipe.level.extreme': 'Ekstrem',
    'swipe.levelOf': 'Tahap {current} daripada {total}',
    'swipe.swipeLeftScam': 'Leret Kiri: Scam',
    'swipe.swipeRightSafe': 'Leret Kanan: Selamat',
    'swipe.dragOrTap': 'Seret kad atau tekan butang',
    'swipe.correct': 'Betul',
    'swipe.notQuite': 'Belum Tepat',
    'swipe.feedbackChoice': 'Anda memilih {choice}. Jawapan betul: {expected}.',
    'swipe.redFlag': 'Amaran Merah',
    'swipe.whyThisMatters': 'Mengapa Ini Penting',
    'swipe.excellent': 'Cemerlang',
    'swipe.goodWork': 'Bagus',
    'swipe.practiceMore': 'Perlu Lebih Latihan',
    'swipe.accuracy': 'Ketepatan',
    'swipe.frictionTier': 'Tahap geseran',
    'swipe.savedOffline': 'Disimpan secara tempatan (mod luar talian)',
    'swipe.syncedApi': 'Disegerakkan dengan API',
    'swipe.playAgain': 'Main Semula',
    'swipe.backToApp': 'Kembali ke Aplikasi',
    'swipe.nextStep.strict': 'Profil ditetapkan ke mod keselamatan KETAT.',
    'swipe.nextStep.balanced': 'Profil ditetapkan ke mod keselamatan SEIMBANG.',
    'swipe.nextStep.light': 'Profil ditetapkan ke mod keselamatan PINTAR.',
    'swipe.surface.messages': 'Mesej',
    'swipe.surface.replyOtp': 'Balas OTP',
    'swipe.surface.ignore': 'Abaikan',
    'swipe.surface.maybankNotice': 'NOTIS RASMI MAYBANK',
    'swipe.surface.subject': 'Subjek',
    'swipe.surface.subjectOtp': 'Log Masuk Luar Biasa Dari Singapura',
    'swipe.surface.subjectRefund': 'Bayaran Balik Cukai Belum Dituntut - RM 850.50',
    'swipe.surface.replyWithOtp': 'Balas dengan OTP',
    'swipe.surface.goSecurePortal': 'Pergi ke Portal Selamat',
    'swipe.surface.online': 'dalam talian',
    'swipe.surface.beneficiaryMismatch': 'Nama penerima tidak sepadan',
    'swipe.surface.incomingCall': 'Panggilan Video Masuk',
    'swipe.surface.unstable': 'TIDAK STABIL',
    'swipe.surface.qrPayRequest': 'Permintaan bayaran QR: RM 1,000 kepada pemandu pihak ketiga',
    'swipe.s1.title': 'Sekatan Akaun Mendesak',
    'swipe.s1.preview': 'Nombor mudah alih tidak dikenali',
    'swipe.s1.message': 'Akaun bank anda DISEKAT! Klik segera untuk sahkan: bit.ly/fake-bank-login',
    'swipe.s1.redFlag': 'Sangat mendesak + URL dipendekkan daripada nombor tidak rasmi.',
    'swipe.s1.education': 'Bank tidak akan menghantar pautan kritikal akaun melalui nombor telefon bimbit biasa.',
    'swipe.s2.title': 'Permintaan OTP Rasmi',
    'swipe.s2.preview': 'Logo + UI kemas',
    'swipe.s2.message': 'Kami mengesan log masuk dari Singapura. Balas dengan OTP 6 digit anda untuk membatalkan transaksi.',
    'swipe.s2.redFlag': 'Meminta anda balas OTP secara terus.',
    'swipe.s2.education': 'OTP ialah tandatangan digital anda. Berkongsinya sama seperti memberi kunci rumah kepada pencuri.',
    'swipe.s3.title': 'Bayaran Balik Cukai LHDN',
    'swipe.s3.preview': 'Kelihatan seperti kepala surat kerajaan',
    'swipe.s3.message': 'Anda mempunyai bayaran balik cukai RM 850.50 yang belum dituntut. Log masuk ke Portal Selamat kami untuk isi butiran bank.',
    'swipe.s3.redFlag': 'Pautan bayaran balik terus dan domain e-mel tidak rasmi.',
    'swipe.s3.education': 'Sentiasa pergi ke laman rasmi gov.my secara manual. Jangan percaya pautan bayaran balik terus dalam e-mel.',
    'swipe.s4.title': 'Rakan Susah',
    'swipe.s4.sender': 'Mak Cik Mary',
    'swipe.s4.preview': 'Foto profil sebenar + permintaan emosi',
    'swipe.s4.message': 'Hi sayang, saya di kedai runcit dan kad gagal. Tolong pindah RM 200 ke akaun ini sekarang.',
    'swipe.s4.redFlag': 'Tekanan + permintaan pindahan ke pemilik akaun tidak dikenali.',
    'swipe.s4.education': 'Sentiasa hubungi individu itu terus untuk sahkan suara sebelum menghantar wang ke akaun tidak dikenali.',
    'swipe.s5.title': 'Panggilan Deepfake / AI',
    'swipe.s5.sender': 'Panggilan Kecemasan Keluarga',
    'swipe.s5.preview': 'Video gelap + bayaran QR mendesak',
    'swipe.s5.message': 'Saya kemalangan, telefon hampir mati, hantar RM 1,000 ke kod QR trak tunda ini SEKARANG.',
    'swipe.s5.redFlag': 'Kecemasan bertekanan tinggi + bayar pihak ketiga serta-merta melalui QR.',
    'swipe.s5.education': 'Scammer guna AI untuk meniru wajah dan suara. Tetapkan kata keselamatan keluarga untuk kecemasan sebenar.',

    'tx.autoReport.title': 'Saluran Laporan Auto',
    'tx.autoReport.descVerify': 'Sediakan laporan keselamatan luar untuk penipuan ini supaya insiden boleh ditingkatkan di luar aplikasi.',
    'tx.autoReport.descBlocked': 'Eksport penipuan yang disekat ini ke saluran keselamatan luar untuk tindakan susulan.',
    'tx.autoReport.button': 'Lapor Penipuan (MCMC + Google)',
    'tx.autoReport.submitting': 'Menghantar...',
    'tx.autoReport.caseReported': 'KES DILAPORKAN',
    'tx.autoReport.successLine1': 'Penipuan ini telah berjaya dilaporkan kepada pihak berkuasa keselamatan. Terima kasih kerana membantu melindungi orang lain.',
    'tx.autoReport.reportedTo': 'Dilaporkan kepada:',
    'tx.autoReport.thankYou': 'Terima kasih kerana menjaga keselamatan komuniti!',
    'tx.autoReport.close': 'Tutup',

    'admin.badge': 'Antara Muka Pentadbir',
    'admin.title': 'Pusat Kawalan Agensi',
    'admin.subtitle': 'Paparan tahap keputusan untuk bank dan agensi menjejak tekanan penipuan serta impak penjimatan.',
    'admin.kpiSavings': 'Anggaran Penjimatan Agensi',
    'admin.kpiBlocked': 'Kes Penipuan Disekat',
    'admin.kpiFlagged': 'Siasatan Ditandai',
    'admin.kpiSavingsDesc': 'Aliran keluar penipuan yang dicegah serta kos triage manual yang dikurangkan melalui sekatan automatik dan keutamaan kes.',
    'admin.kpiBlockedDesc': 'Transaksi berisiko tinggi disekat sebelum kerugian berlaku.',
    'admin.kpiFlaggedDesc': 'Kes ditriage awal untuk tindakan susulan penganalisis yang lebih fokus.',
    'admin.heatmapTitle': 'Peta Haba Penipuan',
    'admin.heatmapSubtitle': 'Insiden mengikut hari dan julat masa',
    'admin.intensity': 'Intensiti:',
    'admin.intensityLow': 'Rendah',
    'admin.intensityMedium': 'Sederhana',
    'admin.intensityHigh': 'Tinggi',
    'admin.savingsChartTitle': 'Penjimatan Agensi (6 Bulan)',
    'admin.savingsChartSubtitle': 'Model kerugian dielak + penjimatan triage',
    'admin.savingsFormula': 'Formula penjimatan: 82% jumlah transaksi disekat + MYR 18 kos operasi dijimatkan bagi setiap kes ditandai atau disekat.',
  },
  zh: {
    'language.label': '语言',
    'language.english': '英语',
    'language.malay': '马来语',
    'language.chinese': '中文',

    'nav.overview': '总览',
    'nav.dashboard': '仪表板',
    'nav.admin': '管理端',
    'nav.transactions': '交易',
    'nav.searchPlaceholder': '搜索...',
    'nav.startTour': '开始导览',
    'nav.profileSettings': '个人资料 / 设置',

    'profile.title': '个人资料与支付安全',
    'profile.subtitle': '管理账户资料、验证状态和已绑定银行卡。',
    'profile.accountDetails': '账户资料',
    'profile.saveChanges': '保存更改',
    'profile.fullName': '姓名',
    'profile.email': '邮箱',
    'profile.phoneNumber': '电话号码',
    'profile.nationality': '国籍',
    'profile.languagePreference': '语言偏好',
    'profile.languageHint': '选择应用界面的显示语言。',
    'profile.applicationTheme': '应用主题',
    'profile.switchDark': '切换到深色',
    'profile.switchLight': '切换到浅色',
    'profile.walletPinProtection': '钱包 PIN 保护',
    'profile.updated': '个人资料已成功更新。',

    'dashboard.blockedFraud': '已拦截诈骗',
    'dashboard.totalTransactions': '交易总数',
    'dashboard.fraudRate': '诈骗率',
    'dashboard.avgReviewTime': '平均审核时间',
    'dashboard.liveFromSimulator': '来自交易模拟器的实时数据',
    'dashboard.flaggedPending': '{count} 个待复核标记',
    'dashboard.flaggedBlockedOverTotal': '标记 + 拦截 / 总数',
    'dashboard.avgFinalRiskScore': '平均最终风险分',
    'dashboard.riskDistribution': '风险分布',
    'dashboard.low': '低',
    'dashboard.medium': '中',
    'dashboard.high': '高',
    'dashboard.realTimeAlerts': '实时告警',
    'dashboard.newCount': '{count} 条新告警',
    'dashboard.noAlerts': '暂无告警。请先触发一笔标记或拦截交易以填充该面板。',
    'dashboard.recentTransactions': '最近交易',
    'dashboard.clearDemoData': '清除演示数据',
    'dashboard.transactionId': '交易 ID',
    'dashboard.user': '用户',
    'dashboard.amount': '金额',
    'dashboard.dateTime': '日期与时间',
    'dashboard.riskScore': '风险分',
    'dashboard.status': '状态',
    'dashboard.blocked': '已拦截',
    'dashboard.flagged': '已标记',
    'dashboard.approved': '已通过',
    'dashboard.noTransactions': '暂无交易。请在 Transaction 页面提交交易以填充此仪表板。',

    'notFound.title': '页面未找到',
    'notFound.line1': '抱歉，您访问的页面不存在。',
    'notFound.line2': '该页面可能已被移动或删除。',
    'notFound.goHome': '返回首页',

    'landing.hero.highlight': '守护',
    'landing.hero.titleRest': '每一笔交易',
    'landing.hero.subtitleLine1': '我们的智能引擎可在毫秒级分析数百万数据点，',
    'landing.hero.subtitleLine2': '为团队提供可执行洞察，保护用户免受数字支付诈骗。',
    'landing.hero.startTour': '开始引导导览',
    'landing.hero.playSwipeShield': '开始 SwipeShield',
    'landing.hero.viewDocs': '查看文档',
    'landing.features.headingLine1': '您值得信赖的',
    'landing.features.headingLine2': '反诈骗伙伴。',
    'landing.features.subLine1': '我们的系统整合并保护不断扩展的',
    'landing.features.subLine2': '专业金融数据生态，以消除威胁。',
    'landing.features.f1Title': '实时检测',
    'landing.features.f1Desc': '即时分析交易并预测诈骗。',
    'landing.features.f2Title': 'AI 风险评分',
    'landing.features.f2Desc': '每笔交易都会获得风险概率评分。',
    'landing.features.f3Title': '智能监控',
    'landing.features.f3Desc': '追踪交易模式，如位置与行为。',
    'landing.features.f4Title': '诈骗告警',
    'landing.features.f4Desc': '高效标记高风险交易。',
    'landing.hiw.title': '工作原理',
    'landing.hiw.s1Title': '用户提交交易',
    'landing.hiw.s1Desc': '交易通过数字网关安全发起。',
    'landing.hiw.s2Title': '系统分析交易特征',
    'landing.hiw.s2Desc': '交叉核验设备指纹、位置与历史模式。',
    'landing.hiw.s3Title': '机器学习模型计算诈骗概率',
    'landing.hiw.s3Desc': '机器学习算法为行为分配风险可能性。',
    'landing.hiw.s4Title': '生成风险分',
    'landing.hiw.s4Desc': '具体风险值决定是否需要干预。',
    'landing.hiw.s5Title': '仪表板展示结果',
    'landing.hiw.s5Desc': '向用户发出告警并自动生成报告。',
    'landing.lesson.badge': '诈骗 101',
    'landing.lesson.title': '防骗安全游戏',
    'landing.lesson.subtitle': '完成 3 轮学习与 3 轮测验。',
    'landing.lesson.scamAware': '反诈意识',
    'landing.lesson.safetyPoints': '安全积分',
    'landing.lesson.completedPrefix': '课程已完成',
    'landing.lesson.correct': '答对',
    'landing.lesson.completedSuffix': '可随时复习，巩固安全习惯。',
    'landing.lesson.intro': '通过 3 张短卡学习基础，并完成 3 道快问快答。',
    'landing.lesson.playAgain': '再玩一次',
    'landing.lesson.startGame': '开始游戏',
    'landing.lesson.learningRound': '学习回合',
    'landing.lesson.quizRound': '测验回合',
    'landing.lesson.rewardRound': '奖励回合',
    'landing.lesson.step': '步骤',
    'landing.lesson.correctFeedback': '回答正确，选择安全。',
    'landing.lesson.wrongFeedback': '下次请尝试更安全的做法。',
    'landing.lesson.missionResult': '任务结果',
    'landing.lesson.youScored': '你获得了 {score}/3。做得好，防骗知识更扎实了。',
    'landing.lesson.rewardLabel': '奖励：+10 安全积分',
    'landing.lesson.nextRound': '下一回合',
    'landing.lesson.claimReward': '领取奖励并完成',
    'landing.lesson.maybeLater': '稍后再说',
    'landing.lesson.selectAnswer': '继续前请先选择一个答案。',
    'landing.lesson.card1Title': '什么是诈骗？',
    'landing.lesson.card1Desc': '诈骗是指有人通过撒谎或隐瞒事实来获取你的金钱、物品或个人信息。',
    'landing.lesson.card2Title': '骗子常见手法',
    'landing.lesson.card2Desc': '他们可能冒充买家、银行或执法人员，催促你在未核实前马上行动。',
    'landing.lesson.card3Title': '简单安全规则',
    'landing.lesson.card3Desc': '先停 10 秒，检查 3 件事：姓名、账号、付款原因。',
    'landing.lesson.q1.question': '哪句话最能说明诈骗？',
    'landing.lesson.q1.o1': '正常商业付款',
    'landing.lesson.q1.o2': '用谎言或骗术骗取他人金钱',
    'landing.lesson.q1.o3': '任何逾期费用',
    'landing.lesson.q2.question': '有人催你紧急转账并说不用核实，最安全做法是什么？',
    'landing.lesson.q2.o1': '因为紧急所以立刻转账',
    'landing.lesson.q2.o2': '先通过可信渠道核实身份',
    'landing.lesson.q2.o3': '先转一半再说',
    'landing.lesson.q3.question': '转账前必须检查什么？',
    'landing.lesson.q3.o1': '只看转账金额',
    'landing.lesson.q3.o2': '收款人姓名、账号与转账原因',
    'landing.lesson.q3.o3': '只看聊天截图',

    'guardian.title': '监护人通知流',
    'guardian.subtitle': '展示由高风险转账或可疑二维码扫描触发的告警。',
    'guardian.backToProfile': '返回个人资料',
    'guardian.refresh': '刷新',
    'guardian.guardianAccount': '监护人账号',
    'guardian.chooseGuardian': '选择监护人',
    'guardian.currentGuardian': '当前监护人',
    'guardian.notSelected': '未选择',
    'guardian.noEmail': '无邮箱',
    'guardian.noPhone': '无电话',
    'guardian.waitingDecision': '等待监护人决定的交易',
    'guardian.pendingCount': '{count} 条待处理',
    'guardian.noPending': '当前没有待处理审批。',
    'guardian.risk': '风险',
    'guardian.to': '至',
    'guardian.approvalId': '审批 ID',
    'guardian.expires': '到期',
    'guardian.approveTransaction': '批准交易',
    'guardian.rejectForSafety': '为安全拒绝',
    'guardian.liveAlertInbox': '实时告警收件箱',
    'guardian.alertCount': '{count} 条告警',
    'guardian.noHighRiskAlerts': '暂无高风险告警。请先触发风险转账或可疑二维码扫描来更新此列表。',
    'guardian.pagePath': '页面路径',
    'guardian.noteApprove': '监护人审核后已批准。',
    'guardian.noteReject': '因诈骗风险已拒绝。',
    'guardian.approvedByGuardian': '交易已由监护人批准。',
    'guardian.rejectedByGuardian': '交易已被监护人拒绝。',
    'guardian.errorLoadGuardians': '无法加载监护人列表。',
    'guardian.errorLoadNotifications': '无法加载监护人通知。',
    'guardian.errorLoadPending': '无法加载待审批记录。',
    'guardian.errorRecordDecision': '无法记录该决定。',
    'guardian.errorLoadDataNow': '当前无法加载监护人数据。',
    'guardian.errorLoadNotificationsNow': '当前无法加载通知。',

    'swipe.channel.sms': '短信',
    'swipe.channel.bankMessage': '银行消息',
    'swipe.channel.email': '邮件',
    'swipe.channel.whatsapp': 'WhatsApp',
    'swipe.channel.videoCall': '视频通话',
    'swipe.channel.message': '消息',
    'swipe.level.veryEasy': '非常简单',
    'swipe.level.easy': '简单',
    'swipe.level.medium': '中等',
    'swipe.level.hard': '困难',
    'swipe.level.extreme': '极限',
    'swipe.levelOf': '第 {current} 关 / 共 {total} 关',
    'swipe.swipeLeftScam': '左滑：诈骗',
    'swipe.swipeRightSafe': '右滑：安全',
    'swipe.dragOrTap': '拖动卡片或点击按钮',
    'swipe.correct': '正确',
    'swipe.notQuite': '还不够准确',
    'swipe.feedbackChoice': '你选择了 {choice}。正确答案：{expected}。',
    'swipe.redFlag': '风险信号',
    'swipe.whyThisMatters': '为什么这很重要',
    'swipe.excellent': '非常好',
    'swipe.goodWork': '做得不错',
    'swipe.practiceMore': '需要更多练习',
    'swipe.accuracy': '准确率',
    'swipe.frictionTier': '风控级别',
    'swipe.savedOffline': '已本地保存（离线模式）',
    'swipe.syncedApi': '已与 API 同步',
    'swipe.playAgain': '再玩一次',
    'swipe.backToApp': '返回应用',
    'swipe.nextStep.strict': '配置已设置为严格安全模式。',
    'swipe.nextStep.balanced': '配置已设置为平衡安全模式。',
    'swipe.nextStep.light': '配置已设置为智能安全模式。',
    'swipe.surface.messages': '信息',
    'swipe.surface.replyOtp': '回复 OTP',
    'swipe.surface.ignore': '忽略',
    'swipe.surface.maybankNotice': 'MAYBANK 官方通知',
    'swipe.surface.subject': '主题',
    'swipe.surface.subjectOtp': '检测到来自新加坡的异常登录',
    'swipe.surface.subjectRefund': '未领取税务退款 - RM 850.50',
    'swipe.surface.replyWithOtp': '回复 OTP',
    'swipe.surface.goSecurePortal': '前往安全门户',
    'swipe.surface.online': '在线',
    'swipe.surface.beneficiaryMismatch': '收款人姓名不匹配',
    'swipe.surface.incomingCall': '来电视频通话',
    'swipe.surface.unstable': '不稳定',
    'swipe.surface.qrPayRequest': '二维码付款请求：RM 1,000 给第三方司机',
    'swipe.s1.title': '账户紧急冻结',
    'swipe.s1.preview': '未知手机号码',
    'swipe.s1.message': '你的银行账户已被冻结！请立即点击验证：bit.ly/fake-bank-login',
    'swipe.s1.redFlag': '极端紧迫感 + 来自非官方号码的短链接。',
    'swipe.s1.education': '银行不会通过普通手机号发送账户关键链接。',
    'swipe.s2.title': '官方 OTP 请求',
    'swipe.s2.preview': '带 Logo + 精致界面',
    'swipe.s2.message': '我们检测到来自新加坡的登录。请回复你的 6 位 OTP 以取消该交易。',
    'swipe.s2.redFlag': '要求你直接回复 OTP。',
    'swipe.s2.education': 'OTP 是你的数字签名。分享 OTP 就像把家门钥匙交给小偷。',
    'swipe.s3.title': 'LHDN 税务退款',
    'swipe.s3.preview': '看起来像政府公函',
    'swipe.s3.message': '你有一笔 RM 850.50 的未领取税务退款。请登录我们的安全门户提交银行资料。',
    'swipe.s3.redFlag': '直接退款链接 + 非官方邮件域名。',
    'swipe.s3.education': '请手动访问官方 gov.my 网站。不要相信邮件中的直接退款链接。',
    'swipe.s4.title': '求助的朋友',
    'swipe.s4.sender': 'Mary 阿姨',
    'swipe.s4.preview': '真实头像 + 情绪化请求',
    'swipe.s4.message': '亲爱的，我在超市刷卡失败了。请现在转 RM 200 到这个账户。',
    'swipe.s4.redFlag': '施压 + 要求转账到陌生账户持有人。',
    'swipe.s4.education': '转账到陌生账号前，务必先语音联系本人确认。',
    'swipe.s5.title': 'Deepfake / AI 通话',
    'swipe.s5.sender': '家庭紧急来电',
    'swipe.s5.preview': '暗光视频 + 紧急二维码付款',
    'swipe.s5.message': '我出车祸了，手机快没电，马上转 RM 1,000 到这个拖车二维码。',
    'swipe.s5.redFlag': '高压紧急情境 + 要求立即向第三方二维码付款。',
    'swipe.s5.education': '骗子会用 AI 模仿脸和声音。请与家人设定紧急安全暗号。',

    'tx.autoReport.title': '自动上报流程',
    'tx.autoReport.descVerify': '为该诈骗准备外部安全报告，以便将事件升级到应用之外处理。',
    'tx.autoReport.descBlocked': '将此被拦截的诈骗导出到外部安全渠道以便后续跟进。',
    'tx.autoReport.button': '上报诈骗（MCMC + Google）',
    'tx.autoReport.submitting': '提交中...',
    'tx.autoReport.caseReported': '案件已上报',
    'tx.autoReport.successLine1': '该诈骗已成功上报给安全机构。感谢你帮助保护更多人。',
    'tx.autoReport.reportedTo': '已上报至：',
    'tx.autoReport.thankYou': '感谢你守护社区安全！',
    'tx.autoReport.close': '关闭',

    'admin.badge': '管理界面',
    'admin.title': '机构指挥中心',
    'admin.subtitle': '为银行与机构提供决策级视图，追踪诈骗压力与节省成效。',
    'admin.kpiSavings': '机构预估节省',
    'admin.kpiBlocked': '已拦截诈骗案件',
    'admin.kpiFlagged': '已标记调查',
    'admin.kpiSavingsDesc': '通过自动拦截与优先级分流，减少诈骗资金流出与人工分诊成本。',
    'admin.kpiBlockedDesc': '在损失发生前拦截高风险交易。',
    'admin.kpiFlaggedDesc': '提前分流案件，让分析师更聚焦地跟进。',
    'admin.heatmapTitle': '诈骗热力图',
    'admin.heatmapSubtitle': '按星期与时段统计事件',
    'admin.intensity': '强度：',
    'admin.intensityLow': '低',
    'admin.intensityMedium': '中',
    'admin.intensityHigh': '高',
    'admin.savingsChartTitle': '机构节省（近6个月）',
    'admin.savingsChartSubtitle': '模型估算：避免损失 + 分诊节省',
    'admin.savingsFormula': '节省公式：被拦截交易金额的82% + 每个标记/拦截案件节省 MYR 18 运维成本。',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const stored = localStorage.getItem(STORAGE_KEY) as LanguageCode | null;
    if (stored === 'en' || stored === 'ms' || stored === 'zh') {
      return stored;
    }
    return 'en';
  });

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.setAttribute('lang', language);
  }, [language]);

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
  };

  const t = useMemo(() => {
    return (key: string) => {
      return translations[language][key] ?? translations.en[key] ?? key;
    };
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
